// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxzimmiytqxqfmjoxhrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4emltbWl5dHF4cWZtam94aHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTg0NDEsImV4cCI6MjA2NjY5NDQ0MX0.1YHWeNX8jnjvN1Fy5HW3abuuMSyHXMN-_M_CI_UWPBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});